title: "PressPal"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2526S1-CS2103T-W08-1/tp"
github_icon: "images/github-icon.png"

# remote_theme: pages-themes/hacker@v0.2.0
plugins:
# - jekyll-remote-theme
